### ISSUE TITLE
County geometry information?

### ISSUE THREAD

**Issue by GemSonic** [nytimes/covid-19-data#29] opened 2020-03-27 18:57 UTC
FIPS are included in data sets, but wondered about the best approach for joining this dataset with geometry information about each county so we can visualize this data over time with Kepler.gl? I am not a data scientist, and so have no experience with Python, so was hoping to be able to work with the data in Kepler without coding.

https://github.com/daniel-lij/keplerTest/blob/master/counties.json has county geometry data as well as FIPS embedded for each county. 

Can someone with more knowledge than me assist in joining this NYT county csv with the json so that we can somehow view the change in data over time in Kepler? I read that csv with geometry data can take WKT, but unsure how to implement into csv so data can easily be read by Kepler. Is it possible to still have a csv file for future inclusion of data that also includes geometry data, or do they have to separately be imported into Kepler?

Had no great progress moving between json and csv. Throwing geojson and other forms into the mix muddles making it work.

Found an article from Medium that can join unemployment data with geometry data, but my limited Python cannot fully grasp it: https://medium.com/vis-gl/visualizing-u-s-county-unemployment-with-kepler-gl-c5f2ed31c71

**Comment by bobmonsour** [comment] 2020-03-27 19:49
@GemSonic Your link to the counties.json data seems to be incorrect. I believe the correct link is https://github.com/daniel-lij/keplerTest/blob/master/counties.json

**Comment by GemSonic** [comment] 2020-03-27 20:47
Thank you @bobmonsour, I have edited the original comment to reflect the originally intended sites.

**Comment by dannguyen** [comment] 2020-03-27 22:10
@GemSonic you're asking for help to do something relatively complicated (and ambitious!) and I'm not qualified enough to know how to best get you there. However, just this week I was trying to find a good county-level shapefile, and I found a great selection from the good folks who run /topojson: https://github.com/topojson/us-atlas

If you're looking for a starting step, I can suggest taking a look at the interactive examples on observablehq: here's a very well known (and instructive) example of a choropleth map showing unemployment by county: https://observablehq.com/@d3/choropleth

**Comment by h2oboxer** [comment] 2020-03-28 03:12
i created a file containing County name, county seat and lat/long. this way you can associate the state/county data with a point within the state. https://data.beta.nyc/dataset/state-county-and-county-seat-data-set

**Comment by josh-byster** [comment] 2020-03-28 07:37
I did something very similar to @h2oboxer in JSON in #51 but just mapping FIPS to name/lat/long.

**Comment by wendyannebeauvais** [comment] 2020-03-28 17:35
I would recommend using ArcGIS (or free equivalent QGIS) or mapping libraries in R for visualisation and spatial exploration. This requires a little expertise but you can find someone who can do this if you don’t want to learn. Happy to help further.

**Comment by BStudent** [comment] 2020-03-29 03:37
Geoms for us counties can be found as shapefiles and some other formats on the US Census bureau web site.  A zip shapefile can be read directly by a geopandas dataframe.  There are examples of how to read census bureau shapefiles in the example section of the geopandas online doc.  You should be able to cut and paste that code directly into a jupyter notebook or Google colab notebook and tweak it to taste.

**Comment by tiffehr** [comment] 2020-05-22 05:19
I have added this discussion to our Project board that collections types of issues, including Additive Data.  I see this topic and conversation as fitting other sources and methods people could use to augment this data set.

I'll close this issue, since it is collected in our Project board.

**Closed by tiffehr** 2020-05-22 05:19 UTC

**Comment by briancpark** [comment] 2020-05-22 07:18
Hey @GemSonic. I’ve actually found a very simple way to import geometric county data with this database and plotly’s GeoJSON mappings. Conveniently it’s all automatic since NYTimes already provides the FIPS metadata. It’s just as simple as joining the COVID-19 `.csv` file with the GeoJSON datafrane through pandas. Example of the code is available in my [repo](https://github.com/briancpark/COVID-19-Visualizations). It helped me create this visualization of the spread

![gif](https://github.com/briancpark/COVID-19-Visualizations/raw/master/timelapses/us_confirmed_timelapse.gif)
