### ISSUE TITLE
Data Issue:  Incorrect data for Ohio 7/2 and 7/3

### ISSUE THREAD

**Issue by stu125** [nytimes/covid-19-data#373] opened 2020-07-06 03:49 UTC
### Describe the issue:
- [x ] Incorrect number of cases or deaths
- [ ] Suspicious number of cases or deaths
- [ ] Missing data for a locality
- [ ] Missing time-series information
- [ ] Other

### Fuller details
The Ohio Department of Health's site was down Thursday afternoon and I believe this led to y'all having zero newly reported cases for Ohio counties on 7/2 followed by a spike representing two days of newly reported cases on 7/3.  From what I've been able to put together y'all use the difference in the cumulative reported cases from Ohio from yesterday to today as case counts. ODH reports the onset data for their new cases, so you could back fill the missing data using the sum of case counts by Onset date--however going forward you'd have to update previous days' cumulative counts to maintain consistency (or rig a kind of two step the bridge the two).  

ODH by county is kept here: https://coronavirus.ohio.gov/static/COVIDSummaryData.csv

There is a similar issue with some of the Indiana data (among others Ripley County is non-monotonoic in this data, Franklin's reports don't match the Indiana State Department of Health)  which could be corrected using this feed: 
https://hub.mph.in.gov/dataset/bd08cdd3-9ab1-4d70-b933-41f9ef7b809d/resource/afaa225d-ac4e-4e80-9190-f6800c366b58/download/covid_report_county_date.xlsx

**Comment by lwaananenjones** [comment] 2020-07-06 16:34
You're correct that county data for Ohio did not update on July 2 because the state did not update its dashboard or county-level counts. We did update the state totals with the case count the state published. Our data is based on the date cases are announced since this is the closest to real-time data that is available from all states. While some states like Ohio do provide cases by date of illness onset, date diagnosed, or date the case was reported to the state, this isn't yet widely or consistently available, especially at the county level. 

In Indiana, we include probable cases and deaths from state data in addition to the lab-confirmed cases displayed on the state's dashboard, which is the difference you're seeing with Franklin County. It is fairly common for case counts to decrease slightly at the county level, often as cases are reassigned to a different county or state based on the person's permanent address. Sometimes we are able to go back and revise for these changes, like if a county's one death is reassigned to a different county, but states make these adjustments so often that we usually do not have enough information to accurately revise previous days, and then we leave the numbers as they were reported. If there are specific Ripley County discrepancies that stand out, we can look into it.

**Comment by stu125** [comment] 2020-07-06 16:55
Our area of interest is the greater Cincinnati area.  Here is the image I use to illustrate the current differences in the sources to our team.  Sharing so you can see the Ripley County error (and it looks like an Adams County, Ohio issue yesterday into today).  If there isn't going to be a change, I'll adjust our county level calculations to account for this 7/2 anomaly going forward.

Thank you.

![2020_07_06_ODH_INDH_NY_Times_Compare](https://user-images.githubusercontent.com/49403531/86618890-a6506c00-bf87-11ea-9484-7288b1bb5d9c.png)

**Comment by amyswalk** [comment] 2020-07-08 00:02
@stu125, thanks very much for your note and the charts. We reviewed the Indiana data (and Adams, Ohio) and the figures in our dataset are the figures that we pulled from the state's data on those dates. The state likely made some adjustments to the case tallies and may have removed cases or moved them to another county. As Lisa mentioned states make these adjustments so frequently and we don't typically have enough information to make accurate revisions. We will leave these figures (and the Ohio data) as reported for now.

**Closed** 2020-07-08 12:54 UTC
Labels: data-issue
