### ISSUE TITLE
Data Issue:  No data for 9/22/21

### ISSUE THREAD

**Issue by Pedro-McM** [nytimes/covid-19-data#627] opened 2021-09-23 13:58 UTC
Hello.  Normally you post a given day's data at the end of the day, but yesterday's (9/22/21) data is still missing.

Just wanted to make sure you're aware of this.

Thanks.

**Comment by tiffehr** [comment] 2021-09-23 14:51
@Pedro-McM Looking into it!

**Comment by tiffehr** [comment] 2021-09-23 18:05
Still looking into it.

**Comment by cfhp1** [comment] 2021-09-23 21:07
This seems like a good time to say again how much we appreciate the service you provide, @tiffehr!

**Comment by tiffehr** [comment] 2021-09-24 03:36
Looks like this may be an issue we'll fix tomorrow. I'll report back.

**Comment by cfhp1** [comment] 2021-09-24 03:40
Thanks for continuing to work on it, @tiffehr. An update in the morning would be _very_ helpful.

**Comment by cfhp1** [comment] 2021-09-24 13:12
I'm a little confused, @tiffehr. Does the comment above and the other thread with both issues closed mean there will be no update today?

**Comment by dawenx** [comment] 2021-09-24 13:12
Thanks @tiffehr @albertsun an update for 09/23 would be greatly appreciated

**Comment by dawenx** [comment] 2021-09-24 13:13
@cfhp1 looks like only #628 is close, pretty sure they are looking into data update issue

**Comment by cfhp1** [comment] 2021-09-24 13:17
@dawenx, thanks. Makes sense that was rolled into this issue.

**Comment by SomervilleTom** [comment] 2021-09-24 14:33
+1 on expressing appreciation for this work. My colleagues and I have been maintaining an [interactive map](https://covid.zeetix.com) of this data since April of 2020. We've integrated the daily CDC vaccination data (for better or worse).

I'm here to check on the delayed updates yesterday and today. I'm glad to see that the issue is being handled -- we'll just defer the update on our site until the issue here is fixed. No big deal.

**Comment by brisbink** [comment] 2021-09-24 14:45
I also want to chime in and say a big thanks to NYT for providing this data. I use the NYT BigQuery public dataset (which I think pulls from this repo) to create a COVID tracking dashboard. I use it every day to stay informed and safe! Thank you thank you thank you.

**Comment by chem-geek** [comment] 2021-09-24 15:59
Yes, thanks for providing this resource for those of us publishing and analyzing data. Looking forward to the resumption of updates after 9/21.

**Comment by DaveBirdsall** [comment] 2021-09-24 16:22
I also use this dataset for a weekly report to a small group of friends. Looking forward to seeing the issues resolved.

**Comment by lwaananenjones** [comment] 2021-09-24 16:43
Hi everyone! The data is now updated. This was related to a one-time glitch related to updates with our publishing system. We're committed to providing daily data updates and don't expect this to be a recurring issue. 

Although we're sorry about the circumstances, it's great to hear about how you're using the data and continuing to maintain your projects after all these months :)

**Comment by cfhp1** [comment] 2021-09-24 16:51
Thank you very much, @lwaananenjones, @tiffehr and anyone else who helped get this going again. I don't suppose it's possible to quantify the impact of your reporting, but I am sure you have saved lives.

**Comment by DaveBirdsall** [comment] 2021-09-24 17:05
Very grateful to @lwaananenjones and @tiffehr and their cohorts for fixing this issue. The data you provide is so valuable.

**Comment by dawenx** [comment] 2021-09-24 17:12
THANKS A LOT @lwaananenjones and @tiffehr and NYT team. [our dashboard for the world](https://nssac.bii.virginia.edu/covid-19/dashboard/) relies on your data for US part and we are committed to update all data daily :)

**Comment by brisbink** [comment] 2021-09-24 17:45
👏👏👏

**Comment by Pedro-McM** [comment] 2021-09-24 19:24
I'll join the chorus:  Thank you to the New York Times and all those working on this project for making this data available.  I check it almost daily and use it for a weekly Covid update that I post to my friends on Facebook.

**Closed** 2021-09-24 22:29 UTC
Labels: data-issue
